### ISSUE TITLE
disallow `@author` in doc block

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/standards-php#10]

**Comment by pbergman** [comment]
why would we want to disallow the `@author` doc block?

**Comment by DoNormal** [comment]
- We already remove these comments if we come across them in code reviews.
- It's doesn't really matter who created the file.
- The whole history of the file is already stored in Git.
- Even worse: most of the time the value is wrong because the class is copied or generated.

**Comment by boudewijn-zicht** [comment]
I've never removed an `@author` tag.  I do agree that there is little need to keeping it because the author information is much better represented in the git history.

I definitely agree with the remark:

> Even worse: most of the time the value is wrong because the class is copied or generated.

**Comment by pbergman** [comment]
yes but a commit is different then a author! The point here is that you could read who created/started  the code and can always ask why he did something. If you want to disable this i would recommend that we enforce a better rule about the the author name in git!

And because people copy/paste (or generated) it wrong is another issue and should not weight in the decision! And should be a responsible of the programmer (and a can also think of allot of other rules you could apply then.)

**Comment by muhammedeminakbulut** [comment]
git gives the tools to track down who created/started a piece of code. so i dont think that's a problem.

What is a better rule to enforce the author name in git?

**Comment by wpbenner** [comment]
Maybe I understand it wrong, but the code review is a measure where everyone is forced to develop code that corresponds to the standard in which each inside Zicht agrees on. So these rules must be followed. So the code that is developed is the same right? Than author is kind of redundant right?

**Comment by pbergman** [comment]
that can be true but a author (person) makes a decision based on experience or documentation how to implement code and has nothing to do with style (this can be to ignore certain errors for example). 

So the author can later be asked why did certain implementation before you going to change parts of the code because should have insight why something is done the way it is done.

But is find this amazing that certain people want to have doc notation when it is not necessary or makes no sense (for example with "simple" migrations). Because similar rules should apply there as well (there should be a git log describing what it does).

**Comment by muhammedeminakbulut** [comment]
decided to implement
