### ISSUE TITLE
Forbid $ret

### ISSUE THREAD

**Issue by DoNormal** [zicht/standards-php#18]
```
$ret = []
foreach ($x as $y) {
   $ret[] = $y;
}

return $ret; // 😢
```

There's only one valid case for a variable name `$ret`:

```
public function getPublicTransportCompaniesFromRotterdam()
{
   return $ret;
}
```

**Comment by boudewijn-zicht** [comment]
One quality of good code is that other developers understand what is meant.  Name one developer, here at Zicht, who does not understand that `$ret` is meant as a placeholder for `$result` or `$returnValue`?

I would strongly suggest people writing `$result` instead of `$ret`, but the primary goal is that other people understand what the code does.  Since `$ret` has that covered, I would allow `$ret` in the code.  Although I would probably comment on it in a PR. :smile:

**Comment by wtfzdotnet** [comment]
Although I voted note with the given example being sufficient, I do prefer variables that make sense like `$genreRepository` instead of `$repository`, `$r`, or whatever you might think of, explicitly defining these properly as such would help anyone understand the code, such as @boudewijn-zicht mentioned already :)

**Comment by muhammedeminakbulut** [comment]
decided not to implement by decision of the core dev team and votes
