### ISSUE TITLE
Trigger error on double quoted strings

### ISSUE THREAD

**Issue by DoNormal** [zicht/standards-php#2]
This should not be allowed:
```
throw new NotFoundHttpException(sprintf("Not able to find slug with title: %s", $slug));
```

**Comment by pbergman** [comment]
this will also not allow this?

`throw new NotFoundHttpException("Not able to find slug with title: ${slug}"));`

**Comment by boudewijn-zicht** [comment]
I agree with disallowing double quotes, assuming that this sniff will still allow the case that @pbergman describes.

**Comment by boudewijn-zicht** [comment]
@muhammedeminakbulut Can you confirm that this sniff does not fire on `"hello ${userName}"`?

**Comment by muhammedeminakbulut** [comment]
the sniff isn't there yet. that should be decided upon. I have a `eval()` feeling with `"my name is $name"`

**Comment by wtfzdotnet** [comment]
- What about docblock's containing annotations, we use double quotes here all over the place?
- Shouldn't we also forbid heredocs then? In favor of nowdocs? 

Just based on how this issue was created without any context I'm giving it a thumbs-down. Aside from that I still have the questions that remain unanswered.

**Comment by muhammedeminakbulut** [comment]
this will be a warning as discussed with the core dev team. not an error.

**Comment by muhammedeminakbulut** [comment]
fixed
