### ISSUE TITLE
When chaining method calls multiline, move the `;` to an separate line.

### ISSUE THREAD

**Issue by wtfzdotnet** [zicht/standards-php#24]
This is in line with the new array comma rule, avoids problems with git ( for say forms etc ).

**Comment by wtfzdotnet** [comment]
```php
        $form
            ->add('title', null, ['required' => true])
            ->add('body', null, ['required' => false])
        ;
```

**Comment by 7ochem** [comment]
I would like to add some arguments into this discussion. I do like to state that personally I do not agree with this suggestion.

## Pro: Git diff

It is true that the suggestion of placing the semicolon on it's own line will make the Git diff only 1 line instead of 2 lines when adding another chained method call at the end of the chain, just like when adding another array element at the end of a multi-line array.

```php
$form
    ->add('title', null, ['required' => true]);
```

When adding another method call, for instance `->add('body', null, ['required' => false])`, then the Git diff will look like this: one line is removed and two lines will be added

```Diff
$form
-    ->add('title', null, ['required' => true]);
+    ->add('title', null, ['required' => true])
+    ->add('body', null, ['required' => false]);
```
When placing the semicolon `;` on it's own line, the diff would look like this: only one line is added
```Diff
$form
    ->add('title', null, ['required' => true])
+    ->add('body', null, ['required' => false])
;
```

However, you could consider if you should change your code style because of a shortcoming of Git?

## PSR
PSR does not state anything about the placing of the semicolon at the end of a statement. So PSR-wise this is a grey area.

## Difference with arrays

Besides the effect on the diff Git is producing, chained method calls and array elements are definitely not "the same", there are a few differences. The first one is that the rule with arrays is adding 1 character, a comma, on an already existing line of code, that's it. This suggestion means adding a whole extra line to your code to place an already present character, the `;` semicolon, on another place in the code.

Secondly you should think about the functional differences, where chained method calls are limited to the available methods in a class and array elements can be as many as you need, so what would be occurring more often? Adding an array element or adding a method to the chain? In a few projects I have scanned, multi-line array definitions occur 120% more often than method chains, so the Git diff "issue" happens a lot less in the case of method chaining.

**Comment by 7ochem** [comment]
Check if current rules do allow this.
