### ISSUE TITLE
Doctrine migrations

### ISSUE THREAD

**Issue by wtfzdotnet** [zicht/standards-php#78]
If we also have to start adding these in our migration classes to conform to standards, I think we are going overboard with this...

https://github.com/zicht/ticket-trigger-football-bundle/pull/504/files#diff-8b65d1b00ed3225abc17c2bf06099987

`// phpcs:disable Zicht.NamingConventions.Classname.InvalidName`

**Comment by 7ochem** [comment]
Agreed. I think it should accept classnames ending with numbers. This "bug" in this rule has never really bothered anyone because we've always had the migrations outside of the scanned directories. But in this case where there is a migration within a bundle it is within the PHPCS scope, it is indeed an issue.

Also with Symfony 4 projects we're going to adhere to the default/recommended Symfony project structure and migrations will be within the PHPCS scope...

**Comment by 7ochem** [comment]
Closing as friendsofphp/php-cs-fixer is the preferred linter now and zicht/standards-php is abandoned.
